[toolchain]
anchor_version = "0.31.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solcron = "5CENHQo5xhRnAXYjFBZ5D9sjM28w7fNm5iyGptbHzrjo"
solcron_registry = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
solcron_execution = "ExecNqpXiPPjs7m5wbuTCxZE8PJzgdW2cWEw23kcKJKm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-basic = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/basic.ts"
test-registry = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/solcron.ts"
test-execution = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/execution.ts"
